ruby '1.9.3'

source 'https://rubygems.org'

gem 'thin'
gem 'sass'
gem 'coffee-script'
gem 'sinatra'
gem "sinatra-twitter-bootstrap", github: "mifo/sinatra-twitter-bootstrap"
gem 'sprockets'
gem 'shotgun'
gem 'foreman'
gem 'mongoid'
gem 'activesupport'
gem 'eco'
gem 'deano'

group :development, :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'pry'
end